- name: docker container clear
  shell: docker ps -a | grep ruby2.1 | awk '{print $1}' | xargs --no-run-if-empty docker rm -f
  tags: ruby2.1
  sudo: yes
- name: docker build
  shell: docker build -t docker/ruby2.1 {{ ansible_env.PWD }}/roles/middlewares/ruby/files/Dockerfiles/ruby2.1/
  tags: ruby2.1
  sudo: yes
