- name: copy ansible file
  tags: always
  copy: src={{ item }} dest="{{ ansible_env.PWD }}"
  with_items:
    - ansible
    - build
- name: docker run (PHP5.6 application)
  shell: docker run -itd --name php5.6 docker/php /sbin/init
  tags: php5.6
  sudo: yes
- name: copy ansible files to container (PHP5.6 application)
  shell: tar -cv * | sudo docker exec -i php5.6 tar x -C /root/ansible chdir=ansible
  tags: php5.6
  sudo: yes
- name: copy test files to container (PHP5.6 application)
  shell: tar -cv * | sudo docker exec -i php5.6 tar x -C /var/tmp chdir=build
  tags: php5.6
  sudo: yes
- name: docker provision (PHP5.6 application with composer)
  shell: docker exec -t php5.6 ansible-playbook -t with_composer -i "localhost," /root/ansible/settings.yml
  tags: with_composer
  sudo: yes
- name: docker provision (PHP5.6 application without composer)
  shell: docker exec -t php5.6 ansible-playbook -i "localhost," /root/ansible/settings.yml
  tags: without_composer
  sudo: yes
