- name: copy ansible file
  tags: php
  copy: src={{ item }} dest="{{ ansible_env.PWD }}"
  with_items:
    - ansible
    - build
    - upload
- name: docker run (%TAG% application)
  shell: docker run -itd --name %APPLICATION%_%TAG% docker/php /sbin/init
  tags: %TAG%
  sudo: yes
- name: copy ansible files to container (%TAG% application)
  shell: tar -cv * | sudo docker exec -i %APPLICATION%_%TAG% tar x -C /root/ansible chdir=ansible
  tags: %TAG%
  sudo: yes
- name: copy test files to container (PHP5.6 application)
  shell: tar -cv * | sudo docker exec -i %APPLICATION%_%TAG% tar x -C /var/tmp chdir=build
  tags: %TAG%
  sudo: yes
- name: copy secret files from external to container (PHP5.6 application)
  shell: tar -cv * | sudo docker exec -i %APPLICATION%_%TAG% tar x -C /var/tmp chdir=upload
  tags: %TAG%
  sudo: yes
- name: docker provision (%TAG% application with composer)
  shell: docker exec -t %APPLICATION%_%TAG% ansible-playbook -t with_composer -i "localhost," /root/ansible/settings.yml
  tags: %TAG%_with_composer
  sudo: yes
- name: docker provision (%TAG% application without composer)
  shell: docker exec -t %APPLICATION%_%TAG% ansible-playbook --skip-tags with_composer -i "localhost," /root/ansible/settings.yml
  tags: %TAG%_without_composer
  sudo: yes
