- name: docker container clear
  shell: docker ps -a | grep php5.6 | awk '{print $1}' | xargs --no-run-if-empty docker rm -f
  sudo: yes
- name: docker build
  shell: docker build -t docker/php5.6 {{ ansible_env.PWD }}/roles/middlewares/php/files/
  sudo: yes
