- name: copy ansible file
  tags: always
  copy: src={{ item }} dest="{{ ansible_env.PWD }}"
  with_items:
    - ansible
    - upload

# Ruby2.2
- name: docker run (Ruby2.2 application)
  shell: docker run -itd --name ruby2.2 docker/ruby /sbin/init
  sudo: yes
- name: copy ansible files to container (Ruby2.2 application)
  shell: tar -cv * | sudo docker exec -i ruby2.2 tar x -C /root/ansible chdir=ansible
  sudo: yes
- name: docker provision (Ruby2.2 application)
  shell: docker exec -t ruby2.2 ansible-playbook -i "localhost," /root/ansible/settings.yml
  sudo: yes
- name: copy secret files from external to container (Ruby2.2 application)
  shell: tar -cv * | sudo docker exec -i ruby2.2 tar x -C /var/tmp chdir=upload
  tags: ruby2.2
  sudo: yes
- name: docker provision (Ruby2.2 application with Gemfile)
  shell: docker exec -t ruby2.2 ansible-playbook -t with_gemfile -i "localhost," /root/ansible/settings.yml
  tags: with_gemfile
  sudo: yes
- name: docker provision (Ruby2.2 application without Gemfile)
  shell: docker exec -t ruby2.2 ansible-playbook -i "localhost," /root/ansible/settings.yml
  tags: without_gemfile
  sudo: yes

# Ruby2.1
- name: docker run (Ruby2.1 application)
  shell: docker run -itd --name ruby2.1 docker/ruby /sbin/init
  sudo: yes
- name: copy ansible files to container (Ruby2.1 application)
  shell: tar -cv * | sudo docker exec -i ruby2.1 tar x -C /root/ansible chdir=ansible
  sudo: yes
- name: docker provision (Ruby2.1 application)
  shell: docker exec -t ruby2.1 ansible-playbook -i "localhost," /root/ansible/settings.yml
  sudo: yes
- name: copy secret files from external to container (Ruby2.1 application)
  shell: tar -cv * | sudo docker exec -i ruby2.1 tar x -C /var/tmp chdir=upload
  tags: ruby2.1
  sudo: yes
- name: docker provision (Ruby2.1 application with Gemfile)
  shell: docker exec -t ruby2.1 ansible-playbook -t with_gemfile -i "localhost," /root/ansible/settings.yml
  tags: with_gemfile
  sudo: yes
- name: docker provision (Ruby2.1 application without Gemfile)
  shell: docker exec -t ruby2.1 ansible-playbook -i "localhost," /root/ansible/settings.yml
  tags: without_gemfile
  sudo: yes

# Ruby2.0
- name: docker run (Ruby2.0 application)
  shell: docker run -itd --name ruby2.0 docker/ruby /sbin/init
  sudo: yes
- name: copy ansible files to container (Ruby2.0 application)
  shell: tar -cv * | sudo docker exec -i ruby2.0 tar x -C /root/ansible chdir=ansible
  sudo: yes
- name: docker provision (Ruby2.0 application)
  shell: docker exec -t ruby2.0 ansible-playbook -i "localhost," /root/ansible/settings.yml
  sudo: yes
- name: copy secret files from external to container (Ruby2.0 application)
  shell: tar -cv * | sudo docker exec -i ruby2.0 tar x -C /var/tmp chdir=upload
  tags: ruby2.0
  sudo: yes
- name: docker provision (Ruby2.0 application with Gemfile)
  shell: docker exec -t ruby2.0 ansible-playbook -t with_gemfile -i "localhost," /root/ansible/settings.yml
  tags: with_gemfile
  sudo: yes
- name: docker provision (Ruby2.0 application without Gemfile)
  shell: docker exec -t ruby2.0 ansible-playbook -i "localhost," /root/ansible/settings.yml
  tags: without_gemfile
  sudo: yes
