- name: copy ansible file
  tags: ruby
  copy: src={{ item }} dest="{{ ansible_env.PWD }}"
  with_items:
    - ansible
    - upload
- name: docker run (%TAG% application)
  shell: docker run -itd --name %APPLICATION%_%TAG% docker/ruby /sbin/init
  tags: %TAG%
  sudo: yes
- name: copy ansible files to container (%TAG% application)
  shell: tar -cv * | sudo docker exec -i %APPLICATION%_%TAG% tar x -C /root/ansible chdir=ansible
  tags: %TAG%
  sudo: yes
- name: docker provision (%TAG% application)
  shell: docker exec -t %APPLICATION%_%TAG% ansible-playbook -i "localhost," /root/ansible/settings.yml
  tags: %TAG%
  sudo: yes
- name: copy secret files from external to container (%TAG% application)
  shell: tar -cv * | sudo docker exec -i %APPLICATION%_%TAG% tar x -C /var/tmp chdir=upload
  tags: %TAG%
  sudo: yes
- name: docker provision (%TAG% application with Gemfile)
  shell: docker exec -t %APPLICATION%_%TAG% ansible-playbook -t with_gemfile -i "localhost," /root/ansible/settings.yml
  tags: %TAG%_with_gemfile
  sudo: yes
- name: docker provision (%TAG% application without Gemfile)
  shell: docker exec -t %APPLICATION%_%TAG% ansible-playbook --skip-tags with_gemfile -i "localhost," /root/ansible/settings.yml
  tags: %TAG%_without_gemfile
  sudo: yes
